# Testing Convex-NMF

In [2]:
import sys
print '\n'.join(sys.path)


/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/pycuda-2015.1.2-py2.7-linux-x86_64.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/appdirs-1.4.0-py2.7.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/pytools-2015.1.2-py2.7.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/PyBrain-0.3.3-py2.7.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/thrift_py-0.9.0-py2.7.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/PyMF-0.3-py2.7.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/cvxopt-1.1.7-py2.7-linux-x86_64.egg
/opt/anaconda/envs/mindlabenv/lib/python2.7/site-packages/argparse-1.3.0-py2.7.egg
/opt/pylearn2
/opt/opencv-3.0.0/build/lib/python2.7/site-packages
/opt/caffe/python
/opt/anaconda/envs/mindlabenv/lib/python27.zip
/opt/anaconda/envs/mindlabenv/lib/python2.7
/opt/anaconda/envs/mindlabenv/lib/python2.7/plat-linux2
/opt/anaconda/envs/mindlabenv/lib/python2.7/lib-tk
/opt/anaconda/envs/mindlabenv/lib

In [12]:
import semantic_methods_toolkit.python.utils.dataset_factory as DatasetFactory
import numpy
from semantic_methods_toolkit.python.unsupervised_technique.cnmf_experiment import CnmfExperiment

In [13]:
data, labels = DatasetFactory.dataset_factory(
    'semantic_methods_toolkit/dataset/iris.mat', options={'data': 'data', 'labels': 'labels'})

In [14]:
print data

[[ 5.0999999   3.5         1.39999998  0.2       ]
 [ 4.9000001   3.          1.39999998  0.2       ]
 [ 4.69999981  3.20000005  1.29999995  0.2       ]
 [ 4.5999999   3.0999999   1.5         0.2       ]
 [ 5.          3.5999999   1.39999998  0.2       ]
 [ 5.4000001   3.9000001   1.70000005  0.40000001]
 [ 4.5999999   3.4000001   1.39999998  0.30000001]
 [ 5.          3.4000001   1.5         0.2       ]
 [ 4.4000001   2.9000001   1.39999998  0.2       ]
 [ 4.9000001   3.0999999   1.5         0.1       ]
 [ 5.4000001   3.70000005  1.5         0.2       ]
 [ 4.80000019  3.4000001   1.60000002  0.2       ]
 [ 4.80000019  3.          1.39999998  0.1       ]
 [ 4.30000019  3.          1.10000002  0.1       ]
 [ 5.80000019  4.          1.20000005  0.2       ]
 [ 5.69999981  4.4000001   1.5         0.40000001]
 [ 5.4000001   3.9000001   1.29999995  0.40000001]
 [ 5.0999999   3.5         1.39999998  0.30000001]
 [ 5.69999981  3.79999995  1.70000005  0.30000001]
 [ 5.0999999   3.79999995  1.5 

In [5]:
options = {
    'k': 3,
    'termination_criterion': {'iter': 10000, 'tol': 1e-10},
    'initialization': 'kkmeans'
}

In [8]:
cnmf_experiment = CnmfExperiment(numpy.float32(data), options)

AttributeError: KernelKMeans instance has no attribute 'monitor'

In [ ]:
labels_pred, results = cnmf_experiment()

In [ ]:
print (
    (data - numpy.dot(numpy.dot(results["H"], results["W"]), data)) ** 2).sum() / (.0 + 150)

##CNMF algorithm by Paez

In [17]:
from kmf import CNMF

ImportError: No module named kmf